### ISSUE TITLE
make install not working

### ISSUE THREAD

**Issue by netzpixel** [westnetz/rechnung#62]
It seams there is no install part in the Makefile therefor the 'make install' doesn't work.

```
.DEFAULT_GOAL := help

.PHONY: help
help:
	@grep -E '^[\.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

.PHONY: check
check: bandit black-check pip-check test ## Run all checks

.PHONY: bandit
bandit: ## Run bandit
	python -m bandit -r rechnung

.PHONY: black-check
black-check: ## Check code formatting
	python -m black --check rechnung

.PHONY: black
black: ## Format code
	python -m black rechnung

.PHONY: test
test: ## Run unittests
	pytest -v rechnung --cov=./ --cov-report term-missing:skip-covered $(PYTEST_ARGS)

.PHONY: pip-check
pip-check: ## Verify that all python package dependencies are met
	python -m pip check

.PHONY: upgrade
upgrade: ## Update all packages as available
	python -m pip install --upgrade-strategy eager --upgrade $$(cat requirements.in | sed -n 's/==.*$$//p')
	python -m pip install --upgrade-strategy eager --upgrade $$(cat requirements-dev.in | sed -n 's/==.*$$//p')

.PHONY: docs
docs:
	rm -f docs/rechnung.rst
	rm -f docs/modules.rst
	sphinx-apidoc -o docs rechnung
	$(MAKE) -C docs clean
	$(MAKE) -C docs html

```

**Comment by olf42** [comment]
Feel free to add a PR.
Other than that, it is intended to be installed via pip or poetry.

**Comment by netzpixel** [comment]
Then please fix the readme. I haven’t found a way to get the project up and running via the provided documentation.

Am 13.12.2021 um 22:30 schrieb olf ***@***.***>:

﻿

Feel free to add a PR.
Other than that, it is intended to be installed via pip or poetry.

**Comment by netzpixel** [comment]
@olf42 I have never used pip nor poetry and I can't find a way to get this project up and running. Can you please update the documentation so a noob like me can start using it without knowledge about the specific programming language?

**Comment by eqvinox** [comment]
@netzpixel no. Please refer the GPLv3 license:

> 15. Disclaimer of Warranty.
>
> THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

We're sharing this software **just in case** others may find it useful and/or might want to **collaborate** on it. It might as well be entirely broken, set your computer on fire, or only work on the second Tuesday of any month if it falls on an even day.

If you don't find this useful and aren't interested in —or capable of, sorry— providing your own efforts, there's nothing further we can do here and you should look for another similar piece of software that works for you.

**Comment by netzpixel** [comment]
Wow Thanks... all I need is help on how to set this up?!

**Comment by eqvinox** [comment]
> Wow Thanks... all I need is help on how to set this up?!

You certainly do. Yet I don't see written anywhere that such help would be included with this software. What made you think we even have the time and capability to offer this help?

**Comment by netzpixel** [comment]
Usually there's a readme which helps you to get the project up and running. In this project that readme tells me to run 'make install'. Doing that results in an error because there is no install part in the makefile. So I'm just stuck at that step of the setup process. So I ask for help. The answer you see above. 
So I ask for help again. All I need is a normal setup 'guide' which is quite normal with every project.
I'm not a python developer, so I have no clue where to start, therefore I just need some help.

**Comment by eqvinox** [comment]
> In this project that readme tells me to run 'make install'. Doing that results in an error because there is no install part in the makefile.

Thanks for reporting that issue, @olf42 has fixed the README to refer to pip.

> So I ask for help again. All I need is a normal setup 'guide' which is quite normal with every project.

So you received something for free and are now unhappy because it's not as good as other things you have also received for free, and now ask us to improve it to make it work for you, also for free.

Just in case you're wondering, this is exactly how we get disasters like the current log4j security apocalypse. Your approach and attitude towards open source software is completely and entirely untenable.
